### ISSUE TITLE
Requirements Upgrade Workflow Is Failing

### ISSUE THREAD

**Issue by feanil** [openedx/xapi-db-load#111]
See https://github.com/openedx/xapi-db-load/actions/runs/9931716594/job/27431976787

The last few runs of the upgrade python requiremnets workflow have been failing. We probably need to intervene manually to figure out why and fix it so that the workflows will work again.

**Comment by bmtcril** [comment]
This should be all set as of this morning: https://github.com/openedx/xapi-db-load/pull/110
